<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Figure 6 Basal Freezing Long After TMT | GP_LONG</title>
  <meta name="description" content="This is an aggregation of all GPs Data." />
  <meta name="generator" content="bookdown 0.40 and GitBook 2.6.7" />

  <meta property="og:title" content="Figure 6 Basal Freezing Long After TMT | GP_LONG" />
  <meta property="og:type" content="book" />
  
  <meta property="og:description" content="This is an aggregation of all GPs Data." />
  <meta name="github-repo" content="rstudio/bookdown-demo" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Figure 6 Basal Freezing Long After TMT | GP_LONG" />
  
  <meta name="twitter:description" content="This is an aggregation of all GPs Data." />
  

<meta name="author" content="JLB" />


<meta name="date" content="2024-02-07" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="elevated-plus-maze.html"/>

<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">TMT.KOR Book of Data</a></li>

<li class="divider"></li>
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> url: your book url like https://bookdown.org/yihui/bookdown</a></li>
<li class="chapter" data-level="2" data-path="timeline-of-experimental-proceedings.html"><a href="timeline-of-experimental-proceedings.html"><i class="fa fa-check"></i><b>2</b> Timeline of Experimental Proceedings</a></li>
<li class="chapter" data-level="3" data-path="freezing-behaviour-during-tmt-presentation.html"><a href="freezing-behaviour-during-tmt-presentation.html"><i class="fa fa-check"></i><b>3</b> Freezing Behaviour During TMT Presentation</a>
<ul>
<li class="chapter" data-level="3.1" data-path="freezing-behaviour-during-tmt-presentation.html"><a href="freezing-behaviour-during-tmt-presentation.html#statistical-analyses"><i class="fa fa-check"></i><b>3.1</b> Statistical Analyses</a>
<ul>
<li class="chapter" data-level="3.1.1" data-path="freezing-behaviour-during-tmt-presentation.html"><a href="freezing-behaviour-during-tmt-presentation.html#two-way-anova-on-freezing-behaivour"><i class="fa fa-check"></i><b>3.1.1</b> Two-way ANOVA on Freezing behaivour</a></li>
<li class="chapter" data-level="3.1.2" data-path="freezing-behaviour-during-tmt-presentation.html"><a href="freezing-behaviour-during-tmt-presentation.html#regressions"><i class="fa fa-check"></i><b>3.1.2</b> Regressions</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="4" data-path="conditioned-place-aversion-to-tmt.html"><a href="conditioned-place-aversion-to-tmt.html"><i class="fa fa-check"></i><b>4</b> Conditioned Place Aversion to TMT</a>
<ul>
<li class="chapter" data-level="4.1" data-path="conditioned-place-aversion-to-tmt.html"><a href="conditioned-place-aversion-to-tmt.html#statistical-analyses-1"><i class="fa fa-check"></i><b>4.1</b> Statistical Analyses</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="elevated-plus-maze.html"><a href="elevated-plus-maze.html"><i class="fa fa-check"></i><b>5</b> Elevated Plus Maze</a>
<ul>
<li class="chapter" data-level="5.1" data-path="elevated-plus-maze.html"><a href="elevated-plus-maze.html#statistical-analyses-2"><i class="fa fa-check"></i><b>5.1</b> Statistical Analyses</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="basal-freezing-long-after-tmt.html"><a href="basal-freezing-long-after-tmt.html"><i class="fa fa-check"></i><b>6</b> Basal Freezing Long After TMT</a>
<ul>
<li class="chapter" data-level="6.1" data-path="basal-freezing-long-after-tmt.html"><a href="basal-freezing-long-after-tmt.html#statistical-analyses-3"><i class="fa fa-check"></i><b>6.1</b> Statistical Analyses</a>
<ul>
<li class="chapter" data-level="6.1.1" data-path="basal-freezing-long-after-tmt.html"><a href="basal-freezing-long-after-tmt.html#time-spent-freezing"><i class="fa fa-check"></i><b>6.1.1</b> Time Spent Freezing</a></li>
<li class="chapter" data-level="6.1.2" data-path="basal-freezing-long-after-tmt.html"><a href="basal-freezing-long-after-tmt.html#freezing-frequency"><i class="fa fa-check"></i><b>6.1.2</b> Freezing Frequency</a></li>
<li class="chapter" data-level="6.1.3" data-path="basal-freezing-long-after-tmt.html"><a href="basal-freezing-long-after-tmt.html#average-duration-of-freeze"><i class="fa fa-check"></i><b>6.1.3</b> Average Duration of Freeze</a></li>
<li class="chapter" data-level="6.1.4" data-path="basal-freezing-long-after-tmt.html"><a href="basal-freezing-long-after-tmt.html#regressions-1"><i class="fa fa-check"></i><b>6.1.4</b> Regressions</a></li>
</ul></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">GP_LONG</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="basal-freezing-long-after-tmt" class="section level1 hasAnchor" number="6">
<h1><span class="header-section-number">Figure 6</span> Basal Freezing Long After TMT<a href="basal-freezing-long-after-tmt.html#basal-freezing-long-after-tmt" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<div class="figure"><span style="display:block;" id="fig:unnamed-chunk-7"></span>
<img src="Panels/5_Long_Panel.png" alt="Timeline of experimental proceedings: 10 days after the single 5-minute exposure to 10% TMT, mice were placed in each side of the conditioning apparatus for 5 minutes and basal levels of freezing were measured (A). Nor-BNI injected mice froze more than saline mice on the TMT-paired side, but not on the neutral side (B). Both drug conditions exhibited a robust increase in freezing relative to their baseline data from 10 days earlier (C). Saline mice decreased freezing between the two sessions whereas NorBNI-treated mice did not (C). The change in freezing behaviour between the two sessions was significantly reduced by NorBNI administration (D). The frequency of freezing was significantly higher for NorBNI injected mice on the TMT-paried side, but not the neutral side (E). Saline but not NorBNI injected mice reduced the frequency of freezing between the two sessions (F). The magnitude of the change between the two sessions was significantly reduced by NorBNI (G). Data presented as mean +/- SEM, * p &lt; 0.05, ** p &lt; 0.01, *** p &lt; 0.001. " width="825" />
<p class="caption">
Figure 6.1: Timeline of experimental proceedings: 10 days after the single 5-minute exposure to 10% TMT, mice were placed in each side of the conditioning apparatus for 5 minutes and basal levels of freezing were measured (A). Nor-BNI injected mice froze more than saline mice on the TMT-paired side, but not on the neutral side (B). Both drug conditions exhibited a robust increase in freezing relative to their baseline data from 10 days earlier (C). Saline mice decreased freezing between the two sessions whereas NorBNI-treated mice did not (C). The change in freezing behaviour between the two sessions was significantly reduced by NorBNI administration (D). The frequency of freezing was significantly higher for NorBNI injected mice on the TMT-paried side, but not the neutral side (E). Saline but not NorBNI injected mice reduced the frequency of freezing between the two sessions (F). The magnitude of the change between the two sessions was significantly reduced by NorBNI (G). Data presented as mean +/- SEM, * p &lt; 0.05, ** p &lt; 0.01, *** p &lt; 0.001.
</p>
</div>
<div id="statistical-analyses-3" class="section level2 hasAnchor" number="6.1">
<h2><span class="header-section-number">6.1</span> Statistical Analyses<a href="basal-freezing-long-after-tmt.html#statistical-analyses-3" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div id="time-spent-freezing" class="section level3 hasAnchor" number="6.1.1">
<h3><span class="header-section-number">6.1.1</span> Time Spent Freezing<a href="basal-freezing-long-after-tmt.html#time-spent-freezing" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>We computed a 2x2 ANOVA with side (Neutral or TMT-paired) as the within subjects factor and Drug condition (Saline or NorBNI) as the between groups factor. This model indicated a significant side * Drug interaction (F(1,38) = 5.69, p = 0.02)</p>
<table>
<thead>
<tr class="header">
<th align="left">Effect</th>
<th align="right">DFn</th>
<th align="right">DFd</th>
<th align="right">F</th>
<th align="right">p</th>
<th align="left">p&lt;.05</th>
<th align="right">ges</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Drug</td>
<td align="right">1</td>
<td align="right">38</td>
<td align="right">11.071</td>
<td align="right">0.002</td>
<td align="left">*</td>
<td align="right">0.195</td>
</tr>
<tr class="even">
<td align="left">variable</td>
<td align="right">1</td>
<td align="right">38</td>
<td align="right">2.542</td>
<td align="right">0.119</td>
<td align="left"></td>
<td align="right">0.011</td>
</tr>
<tr class="odd">
<td align="left">Drug:variable</td>
<td align="right">1</td>
<td align="right">38</td>
<td align="right">5.693</td>
<td align="right">0.022</td>
<td align="left">*</td>
<td align="right">0.025</td>
</tr>
</tbody>
</table>
<p>Follow-up comparisons of the significant interaction indicated that the difference in time spent freezing between Saline and Nor-BNI treated mice was not significant on the neutral size (p = 0.059), but Nor-BNI injected mice spent significantly more time freezing in the the TMT-paired compartment (p &lt; 0.001).</p>
<table style="width:100%;">
<colgroup>
<col width="16%" />
<col width="7%" />
<col width="8%" />
<col width="10%" />
<col width="3%" />
<col width="3%" />
<col width="10%" />
<col width="11%" />
<col width="10%" />
<col width="16%" />
</colgroup>
<thead>
<tr class="header">
<th align="left">variable</th>
<th align="left">.y.</th>
<th align="left">group1</th>
<th align="left">group2</th>
<th align="right">n1</th>
<th align="right">n2</th>
<th align="right">p</th>
<th align="left">p.signif</th>
<th align="right">p.adj</th>
<th align="left">p.adj.signif</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Neutral side</td>
<td align="left">value</td>
<td align="left">Saline</td>
<td align="left">Nor-BNI</td>
<td align="right">19</td>
<td align="right">21</td>
<td align="right">0.05780</td>
<td align="left">ns</td>
<td align="right">0.05780</td>
<td align="left">ns</td>
</tr>
<tr class="even">
<td align="left">TMT side</td>
<td align="left">value</td>
<td align="left">Saline</td>
<td align="left">Nor-BNI</td>
<td align="right">19</td>
<td align="right">21</td>
<td align="right">0.00015</td>
<td align="left">***</td>
<td align="right">0.00015</td>
<td align="left">***</td>
</tr>
</tbody>
</table>
<p>Saline-treated mice exhibited a decrease in time spent freezing between the first and the second session of the long after test (p = 0.003) whereas TMT-treated mice did not decrease freezing between the two sessions (p =0.62).</p>
<table>
<colgroup>
<col width="9%" />
<col width="7%" />
<col width="16%" />
<col width="11%" />
<col width="3%" />
<col width="3%" />
<col width="13%" />
<col width="3%" />
<col width="7%" />
<col width="7%" />
<col width="16%" />
</colgroup>
<thead>
<tr class="header">
<th align="left">Drug</th>
<th align="left">.y.</th>
<th align="left">group1</th>
<th align="left">group2</th>
<th align="right">n1</th>
<th align="right">n2</th>
<th align="right">statistic</th>
<th align="right">df</th>
<th align="right">p</th>
<th align="right">p.adj</th>
<th align="left">p.adj.signif</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Saline</td>
<td align="left">value</td>
<td align="left">Neutral side</td>
<td align="left">TMT side</td>
<td align="right">19</td>
<td align="right">19</td>
<td align="right">3.4548388</td>
<td align="right">18</td>
<td align="right">0.003</td>
<td align="right">0.003</td>
<td align="left">**</td>
</tr>
<tr class="even">
<td align="left">Nor-BNI</td>
<td align="left">value</td>
<td align="left">Neutral side</td>
<td align="left">TMT side</td>
<td align="right">21</td>
<td align="right">21</td>
<td align="right">-0.4979122</td>
<td align="right">20</td>
<td align="right">0.624</td>
<td align="right">0.624</td>
<td align="left">ns</td>
</tr>
</tbody>
</table>
<p>Additionally, the change in freezing behaviour between the two sessions was significantly greater for Saline-treated mice than for NorBNI (t(38) = 2.43, p = 0.01)</p>
<pre><code>## 
##  Welch Two Sample t-test
## 
## data:  change by Drug
## t = -2.4301, df = 35.605, p-value = 0.02027
## alternative hypothesis: true difference in means between group Saline and group Nor-BNI is not equal to 0
## 95 percent confidence interval:
##  -27.018872  -2.430953
## sample estimates:
##  mean in group Saline mean in group Nor-BNI 
##            -12.281579              2.443333</code></pre>
</div>
<div id="freezing-frequency" class="section level3 hasAnchor" number="6.1.2">
<h3><span class="header-section-number">6.1.2</span> Freezing Frequency<a href="basal-freezing-long-after-tmt.html#freezing-frequency" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>We also computed a 2x2 ANOVA on freezing frequency, which also indicated a Drug*Timepoint interaction (F(1,38) = 7.26, p = 0.01).</p>
<table>
<thead>
<tr class="header">
<th align="left">Effect</th>
<th align="right">DFn</th>
<th align="right">DFd</th>
<th align="right">F</th>
<th align="right">p</th>
<th align="left">p&lt;.05</th>
<th align="right">ges</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Drug</td>
<td align="right">1</td>
<td align="right">38</td>
<td align="right">4.708</td>
<td align="right">0.036000</td>
<td align="left">*</td>
<td align="right">0.093</td>
</tr>
<tr class="even">
<td align="left">variable</td>
<td align="right">1</td>
<td align="right">38</td>
<td align="right">12.972</td>
<td align="right">0.000902</td>
<td align="left">*</td>
<td align="right">0.055</td>
</tr>
<tr class="odd">
<td align="left">Drug:variable</td>
<td align="right">1</td>
<td align="right">38</td>
<td align="right">7.257</td>
<td align="right">0.010000</td>
<td align="left">*</td>
<td align="right">0.032</td>
</tr>
</tbody>
</table>
<p>Follow-up comparisons of the significant interaction indicated that there was no effect of Drug treatment on the frequency of freezing on the neutral size (p = 0.45), but Nor-BNI injected mice spent significantly more time freezing than saline-treated mice in the the TMT-paired compartment (p &lt; 0.001).</p>
<table style="width:100%;">
<colgroup>
<col width="16%" />
<col width="7%" />
<col width="8%" />
<col width="10%" />
<col width="3%" />
<col width="3%" />
<col width="10%" />
<col width="11%" />
<col width="10%" />
<col width="16%" />
</colgroup>
<thead>
<tr class="header">
<th align="left">variable</th>
<th align="left">.y.</th>
<th align="left">group1</th>
<th align="left">group2</th>
<th align="right">n1</th>
<th align="right">n2</th>
<th align="right">p</th>
<th align="left">p.signif</th>
<th align="right">p.adj</th>
<th align="left">p.adj.signif</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Neutral side</td>
<td align="left">value</td>
<td align="left">Saline</td>
<td align="left">Nor-BNI</td>
<td align="right">19</td>
<td align="right">21</td>
<td align="right">0.45600</td>
<td align="left">ns</td>
<td align="right">0.45600</td>
<td align="left">ns</td>
</tr>
<tr class="even">
<td align="left">TMT side</td>
<td align="left">value</td>
<td align="left">Saline</td>
<td align="left">Nor-BNI</td>
<td align="right">19</td>
<td align="right">21</td>
<td align="right">0.00063</td>
<td align="left">***</td>
<td align="right">0.00063</td>
<td align="left">***</td>
</tr>
</tbody>
</table>
<p>Saline-treated mice exhibited a decrease in the frequency of freezing between the first and the second session of the long after test (p = &lt;0.001) whereas TMT-treated mice did not decrease freezing between the two sessions (p = 0.53).</p>
<table style="width:100%;">
<colgroup>
<col width="9%" />
<col width="7%" />
<col width="15%" />
<col width="10%" />
<col width="3%" />
<col width="3%" />
<col width="11%" />
<col width="3%" />
<col width="9%" />
<col width="9%" />
<col width="15%" />
</colgroup>
<thead>
<tr class="header">
<th align="left">Drug</th>
<th align="left">.y.</th>
<th align="left">group1</th>
<th align="left">group2</th>
<th align="right">n1</th>
<th align="right">n2</th>
<th align="right">statistic</th>
<th align="right">df</th>
<th align="right">p</th>
<th align="right">p.adj</th>
<th align="left">p.adj.signif</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Saline</td>
<td align="left">value</td>
<td align="left">Neutral side</td>
<td align="left">TMT side</td>
<td align="right">19</td>
<td align="right">19</td>
<td align="right">4.6050714</td>
<td align="right">18</td>
<td align="right">0.00022</td>
<td align="right">0.00022</td>
<td align="left">***</td>
</tr>
<tr class="even">
<td align="left">Nor-BNI</td>
<td align="left">value</td>
<td align="left">Neutral side</td>
<td align="left">TMT side</td>
<td align="right">21</td>
<td align="right">21</td>
<td align="right">0.6281951</td>
<td align="right">20</td>
<td align="right">0.53700</td>
<td align="right">0.53700</td>
<td align="left">ns</td>
</tr>
</tbody>
</table>
<p>Additionally, the change in freezing behaviour between the two sessions was significantly greater for Saline-treated mice than for NorBNI (t(38) = 2.71, p = 0.01)</p>
<pre><code>## 
##  Welch Two Sample t-test
## 
## data:  change by Drug
## t = -2.7084, df = 38, p-value = 0.01008
## alternative hypothesis: true difference in means between group Saline and group Nor-BNI is not equal to 0
## 95 percent confidence interval:
##  -25.186925  -3.640142
## sample estimates:
##  mean in group Saline mean in group Nor-BNI 
##            -16.842105             -2.428571</code></pre>
</div>
<div id="average-duration-of-freeze" class="section level3 hasAnchor" number="6.1.3">
<h3><span class="header-section-number">6.1.3</span> Average Duration of Freeze<a href="basal-freezing-long-after-tmt.html#average-duration-of-freeze" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Repeated measures ANOVA on the average duration of freezing episode indicated a main effect of drug only (F (1,38) = 15.71, p &lt; 0.001).</p>
<table>
<thead>
<tr class="header">
<th align="left">Effect</th>
<th align="right">DFn</th>
<th align="right">DFd</th>
<th align="right">F</th>
<th align="right">p</th>
<th align="left">p&lt;.05</th>
<th align="right">ges</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Drug</td>
<td align="right">1</td>
<td align="right">38</td>
<td align="right">15.713</td>
<td align="right">0.000314</td>
<td align="left">*</td>
<td align="right">0.252</td>
</tr>
<tr class="even">
<td align="left">variable</td>
<td align="right">1</td>
<td align="right">38</td>
<td align="right">1.561</td>
<td align="right">0.219000</td>
<td align="left"></td>
<td align="right">0.007</td>
</tr>
<tr class="odd">
<td align="left">Drug:variable</td>
<td align="right">1</td>
<td align="right">38</td>
<td align="right">1.716</td>
<td align="right">0.198000</td>
<td align="left"></td>
<td align="right">0.008</td>
</tr>
</tbody>
</table>
<p>Nor-BNI treated mice exhibited a significantly higher average duration of freezing episode than did saline-injected mice on both the neutral (p = 0.001) and the TMT-paired (p &lt; 0.001) sides of the CPA apparatus.</p>
<table style="width:100%;">
<colgroup>
<col width="16%" />
<col width="7%" />
<col width="8%" />
<col width="10%" />
<col width="3%" />
<col width="3%" />
<col width="10%" />
<col width="11%" />
<col width="10%" />
<col width="16%" />
</colgroup>
<thead>
<tr class="header">
<th align="left">variable</th>
<th align="left">.y.</th>
<th align="left">group1</th>
<th align="left">group2</th>
<th align="right">n1</th>
<th align="right">n2</th>
<th align="right">p</th>
<th align="left">p.signif</th>
<th align="right">p.adj</th>
<th align="left">p.adj.signif</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Neutral side</td>
<td align="left">value</td>
<td align="left">Saline</td>
<td align="left">Nor-BNI</td>
<td align="right">19</td>
<td align="right">21</td>
<td align="right">0.00107</td>
<td align="left">**</td>
<td align="right">0.00107</td>
<td align="left">**</td>
</tr>
<tr class="even">
<td align="left">TMT side</td>
<td align="left">value</td>
<td align="left">Saline</td>
<td align="left">Nor-BNI</td>
<td align="right">19</td>
<td align="right">21</td>
<td align="right">0.00074</td>
<td align="left">***</td>
<td align="right">0.00074</td>
<td align="left">***</td>
</tr>
</tbody>
</table>
<p>The within-subjects change in the average duration of freezing episode between the two sessions was not significant for either NorBNI-injected (p = 0.13) or saline-injected (p = 0.96) mice.</p>
<table style="width:100%;">
<colgroup>
<col width="10%" />
<col width="7%" />
<col width="16%" />
<col width="11%" />
<col width="3%" />
<col width="3%" />
<col width="12%" />
<col width="3%" />
<col width="7%" />
<col width="7%" />
<col width="16%" />
</colgroup>
<thead>
<tr class="header">
<th align="left">Drug</th>
<th align="left">.y.</th>
<th align="left">group1</th>
<th align="left">group2</th>
<th align="right">n1</th>
<th align="right">n2</th>
<th align="right">statistic</th>
<th align="right">df</th>
<th align="right">p</th>
<th align="right">p.adj</th>
<th align="left">p.adj.signif</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Saline</td>
<td align="left">value</td>
<td align="left">Neutral side</td>
<td align="left">TMT side</td>
<td align="right">19</td>
<td align="right">19</td>
<td align="right">0.055716</td>
<td align="right">18</td>
<td align="right">0.956</td>
<td align="right">0.956</td>
<td align="left">ns</td>
</tr>
<tr class="even">
<td align="left">Nor-BNI</td>
<td align="left">value</td>
<td align="left">Neutral side</td>
<td align="left">TMT side</td>
<td align="right">21</td>
<td align="right">21</td>
<td align="right">-1.572287</td>
<td align="right">20</td>
<td align="right">0.132</td>
<td align="right">0.132</td>
<td align="left">ns</td>
</tr>
</tbody>
</table>
</div>
<div id="regressions-1" class="section level3 hasAnchor" number="6.1.4">
<h3><span class="header-section-number">6.1.4</span> Regressions<a href="basal-freezing-long-after-tmt.html#regressions-1" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>To investigate how each the frequency and the average duration of freezing contribute to the total amount of freezing during the session, we computed regression models with either Frequency or Average duration entered as the predictor and % Freezing entered as the dependent variable.</p>
<div class="sourceCode" id="cb3"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb3-1"><a href="basal-freezing-long-after-tmt.html#cb3-1" tabindex="-1"></a><span class="co"># A regression model</span></span>
<span id="cb3-2"><a href="basal-freezing-long-after-tmt.html#cb3-2" tabindex="-1"></a>a <span class="ot">&lt;-</span> <span class="fu">lm</span>(Perc<span class="sc">~</span>Frz_Freq <span class="sc">*</span> Drug <span class="sc">+</span> Task, <span class="at">data=</span>TwoWeeksFrz_data)</span>
<span id="cb3-3"><a href="basal-freezing-long-after-tmt.html#cb3-3" tabindex="-1"></a><span class="fu">summary</span>(a)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = Perc ~ Frz_Freq * Drug + Task, data = TwoWeeksFrz_data)
## 
## Residuals:
##    Min     1Q Median     3Q    Max 
## -5.871 -2.318 -0.202  1.202 11.596 
## 
## Coefficients:
##                      Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)          -3.55899    1.40642  -2.531   0.0135 *  
## Frz_Freq              0.30168    0.02485  12.141   &lt;2e-16 ***
## DrugNor-BNI          -1.82331    2.02100  -0.902   0.3698    
## TaskTMT side          1.39949    0.75210   1.861   0.0667 .  
## Frz_Freq:DrugNor-BNI  0.09288    0.03535   2.628   0.0104 *  
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 3.24 on 75 degrees of freedom
## Multiple R-squared:  0.8685, Adjusted R-squared:  0.8615 
## F-statistic: 123.9 on 4 and 75 DF,  p-value: &lt; 2.2e-16</code></pre>
<div class="sourceCode" id="cb5"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb5-1"><a href="basal-freezing-long-after-tmt.html#cb5-1" tabindex="-1"></a><span class="co"># Re-order the &quot;drug&quot; variable to get the intercept for the NorBNI group.</span></span>
<span id="cb5-2"><a href="basal-freezing-long-after-tmt.html#cb5-2" tabindex="-1"></a>b <span class="ot">&lt;-</span> TwoWeeksFrz_data</span>
<span id="cb5-3"><a href="basal-freezing-long-after-tmt.html#cb5-3" tabindex="-1"></a>b<span class="sc">$</span>Drug <span class="ot">&lt;-</span> <span class="fu">as.character</span>(b<span class="sc">$</span>Drug)</span>
<span id="cb5-4"><a href="basal-freezing-long-after-tmt.html#cb5-4" tabindex="-1"></a>b<span class="sc">$</span>Drug <span class="ot">&lt;-</span> <span class="fu">factor</span>(b<span class="sc">$</span>Drug,<span class="at">levels =</span> <span class="fu">c</span>(<span class="st">&quot;Nor-BNI&quot;</span>,<span class="st">&quot;Saline&quot;</span>))</span>
<span id="cb5-5"><a href="basal-freezing-long-after-tmt.html#cb5-5" tabindex="-1"></a></span>
<span id="cb5-6"><a href="basal-freezing-long-after-tmt.html#cb5-6" tabindex="-1"></a><span class="co"># A different version of the same regression model</span></span>
<span id="cb5-7"><a href="basal-freezing-long-after-tmt.html#cb5-7" tabindex="-1"></a>a <span class="ot">&lt;-</span> <span class="fu">lm</span>(Perc<span class="sc">~</span>Frz_Freq <span class="sc">*</span> Drug <span class="sc">+</span> Task, <span class="at">data=</span>b)</span>
<span id="cb5-8"><a href="basal-freezing-long-after-tmt.html#cb5-8" tabindex="-1"></a><span class="fu">summary</span>(a)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = Perc ~ Frz_Freq * Drug + Task, data = b)
## 
## Residuals:
##    Min     1Q Median     3Q    Max 
## -5.871 -2.318 -0.202  1.202 11.596 
## 
## Coefficients:
##                     Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)         -5.38230    1.64750  -3.267  0.00164 ** 
## Frz_Freq             0.39456    0.02545  15.506  &lt; 2e-16 ***
## DrugSaline           1.82331    2.02100   0.902  0.36985    
## TaskTMT side         1.39949    0.75210   1.861  0.06669 .  
## Frz_Freq:DrugSaline -0.09288    0.03535  -2.628  0.01042 *  
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 3.24 on 75 degrees of freedom
## Multiple R-squared:  0.8685, Adjusted R-squared:  0.8615 
## F-statistic: 123.9 on 4 and 75 DF,  p-value: &lt; 2.2e-16</code></pre>
<p>The first model accounted for 86% of the variability in time spent freezing (F(4,75) = 123.9, Adjusted R^2 = 0.86, p &lt; 0.001), and indicated that Freezing frequency was a strong independent predictor of total time freezing (t(76) = 12.14, p &lt; 0.001). The model also indicated a significant Frequency * Drug interaction (t(76) = 2.63, p = 0.01). We evaluated the simple effects to further contextualize the significant interaction. Among saline-treated mice, a 10-unit increase in freezing frequency was associated with a 3% increase in total time spent freezing whereas for NorBNI-injected mice, a 10-unit increase in frequency was associated with a 3.9% increase in freezing among Nor-BNI treated mice. In other words, there was a 30% increase in the estimated magnitude of the relationship between the frequency of freezing and total time spent freezing for mice injected with NorBNI.</p>
<div class="sourceCode" id="cb7"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb7-1"><a href="basal-freezing-long-after-tmt.html#cb7-1" tabindex="-1"></a><span class="co"># Model 2: X=Av_Dur, y=Perc</span></span>
<span id="cb7-2"><a href="basal-freezing-long-after-tmt.html#cb7-2" tabindex="-1"></a>a <span class="ot">&lt;-</span> <span class="fu">lm</span>(Perc<span class="sc">~</span>Av_Dur <span class="sc">*</span> Drug <span class="sc">+</span> Task, <span class="at">data=</span>TwoWeeksFrz_data)</span>
<span id="cb7-3"><a href="basal-freezing-long-after-tmt.html#cb7-3" tabindex="-1"></a><span class="fu">summary</span>(a)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = Perc ~ Av_Dur * Drug + Task, data = TwoWeeksFrz_data)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -11.1228  -3.0015  -0.0514   3.2502   8.8207 
## 
## Coefficients:
##                    Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)         -10.528      3.295  -3.195  0.00205 ** 
## Av_Dur               33.903      4.666   7.266 2.93e-10 ***
## DrugNor-BNI           2.655      4.384   0.606  0.54667    
## TaskTMT side         -2.629      1.044  -2.518  0.01393 *  
## Av_Dur:DrugNor-BNI   -3.244      5.623  -0.577  0.56572    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 4.64 on 75 degrees of freedom
## Multiple R-squared:  0.7304, Adjusted R-squared:  0.716 
## F-statistic: 50.79 on 4 and 75 DF,  p-value: &lt; 2.2e-16</code></pre>
<p>The second model accounted for 70% of the variability in time spent freezing (Adjusted R^2 = 0.70). The simple effects found that although average duration of freezing episode was a strong independent predictor of freezing time (t(76) = 7.03, p &lt; 0.001), there was no interaction between this predictor and drug treatment (p = 0.56). A 0.1-second increase in the average duration of freezing episode was associated with a 3% increase in time freezing.</p>
<p>I have taught this course previously at UTM (Summer 2024).</p>
<p>I have been conducting independent research in lab-based settings for over 10 years. I hold a Honours BA an MA from Brock University, and I am a late-stage PhD candidate in the department of psychology at UTM. I am uniquely positioned to provide guidance to UTM students about research opportunities that are available at UTM.</p>

</div>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="elevated-plus-maze.html" class="navigation navigation-prev navigation-unique" aria-label="Previous page"><i class="fa fa-angle-left"></i></a>

    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/USERNAME/REPO/edit/BRANCH/05-GP_LONG.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["_main.pdf", "_main.epub"],
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "subsection"
}
});
});
</script>

</body>

</html>
