<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Figure 3 Freezing Behaviour During TMT Presentation | GP_TMT_Freezing</title>
  <meta name="description" content="This is an aggregation of all GPs Data." />
  <meta name="generator" content="bookdown 0.40 and GitBook 2.6.7" />

  <meta property="og:title" content="Figure 3 Freezing Behaviour During TMT Presentation | GP_TMT_Freezing" />
  <meta property="og:type" content="book" />
  
  <meta property="og:description" content="This is an aggregation of all GPs Data." />
  <meta name="github-repo" content="rstudio/bookdown-demo" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Figure 3 Freezing Behaviour During TMT Presentation | GP_TMT_Freezing" />
  
  <meta name="twitter:description" content="This is an aggregation of all GPs Data." />
  

<meta name="author" content="JLB" />


<meta name="date" content="2024-02-07" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="generate-a-timeline-of-experimental-proceedings.html"/>
<link rel="next" href="conditioned-place-aversion-to-tmt.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">TMT.KOR Book of Data</a></li>

<li class="divider"></li>
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> url: your book url like https://bookdown.org/yihui/bookdown</a></li>
<li class="chapter" data-level="" data-path="project-overview.html"><a href="project-overview.html"><i class="fa fa-check"></i>Project Overview</a></li>
<li class="chapter" data-level="2" data-path="generate-a-timeline-of-experimental-proceedings.html"><a href="generate-a-timeline-of-experimental-proceedings.html"><i class="fa fa-check"></i><b>2</b> Generate a Timeline of Experimental Proceedings</a></li>
<li class="chapter" data-level="3" data-path="freezing-behaviour-during-tmt-presentation.html"><a href="freezing-behaviour-during-tmt-presentation.html"><i class="fa fa-check"></i><b>3</b> Freezing Behaviour During TMT Presentation</a>
<ul>
<li class="chapter" data-level="3.1" data-path="freezing-behaviour-during-tmt-presentation.html"><a href="freezing-behaviour-during-tmt-presentation.html#statistical-analyses"><i class="fa fa-check"></i><b>3.1</b> Statistical Analyses</a>
<ul>
<li class="chapter" data-level="3.1.1" data-path="freezing-behaviour-during-tmt-presentation.html"><a href="freezing-behaviour-during-tmt-presentation.html#two-way-anova-on-freezing-behaivour"><i class="fa fa-check"></i><b>3.1.1</b> Two-way ANOVA on Freezing behaivour</a></li>
<li class="chapter" data-level="3.1.2" data-path="freezing-behaviour-during-tmt-presentation.html"><a href="freezing-behaviour-during-tmt-presentation.html#regressions"><i class="fa fa-check"></i><b>3.1.2</b> Regressions</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="4" data-path="conditioned-place-aversion-to-tmt.html"><a href="conditioned-place-aversion-to-tmt.html"><i class="fa fa-check"></i><b>4</b> Conditioned Place Aversion to TMT</a>
<ul>
<li class="chapter" data-level="4.1" data-path="conditioned-place-aversion-to-tmt.html"><a href="conditioned-place-aversion-to-tmt.html#statistical-analyses-1"><i class="fa fa-check"></i><b>4.1</b> Statistical Analyses</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="elevated-plus-maze.html"><a href="elevated-plus-maze.html"><i class="fa fa-check"></i><b>5</b> Elevated Plus Maze</a>
<ul>
<li class="chapter" data-level="5.1" data-path="elevated-plus-maze.html"><a href="elevated-plus-maze.html#statistical-analyses-2"><i class="fa fa-check"></i><b>5.1</b> Statistical Analyses</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="basal-freezing-long-after-tmt.html"><a href="basal-freezing-long-after-tmt.html"><i class="fa fa-check"></i><b>6</b> Basal Freezing Long After TMT</a>
<ul>
<li class="chapter" data-level="6.1" data-path="basal-freezing-long-after-tmt.html"><a href="basal-freezing-long-after-tmt.html#statistical-analyses-3"><i class="fa fa-check"></i><b>6.1</b> Statistical Analyses</a>
<ul>
<li class="chapter" data-level="6.1.1" data-path="basal-freezing-long-after-tmt.html"><a href="basal-freezing-long-after-tmt.html#time-spent-freezing"><i class="fa fa-check"></i><b>6.1.1</b> Time Spent Freezing</a></li>
<li class="chapter" data-level="6.1.2" data-path="basal-freezing-long-after-tmt.html"><a href="basal-freezing-long-after-tmt.html#freezing-frequency"><i class="fa fa-check"></i><b>6.1.2</b> Freezing Frequency</a></li>
<li class="chapter" data-level="6.1.3" data-path="basal-freezing-long-after-tmt.html"><a href="basal-freezing-long-after-tmt.html#average-duration-of-freeze"><i class="fa fa-check"></i><b>6.1.3</b> Average Duration of Freeze</a></li>
<li class="chapter" data-level="6.1.4" data-path="basal-freezing-long-after-tmt.html"><a href="basal-freezing-long-after-tmt.html#regressions-1"><i class="fa fa-check"></i><b>6.1.4</b> Regressions</a></li>
</ul></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">GP_TMT_Freezing</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="freezing-behaviour-during-tmt-presentation" class="section level1 hasAnchor" number="3">
<h1><span class="header-section-number">Figure 3</span> Freezing Behaviour During TMT Presentation<a href="freezing-behaviour-during-tmt-presentation.html#freezing-behaviour-during-tmt-presentation" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<div class="figure"><span style="display:block;" id="fig:unnamed-chunk-3"></span>
<img src="Panels/2_Frz_Panel.png" alt="Kappa-opioid receptor antagonism modulates basal and stress-induced freezing. (A) CPP was conducted such that each mouse was exposed to TMT for 5-minutes on their preferred side of the behavioural testing apparatus. (B) NorBNI administration 24hours before testing increases basal freezing and decreases freezing during TMT presentation. (C) The number of freezing episodes was increased at Neutral by NorBNI administration. (D) NorBNI did not produce any changes in the average duration of freezing episode under basal conditions or during TMT exposure. All mice exhibit an increase in the % Freezing between the Neutral and TMT sessions (E), but only the saline group increased the number of freezing episodes between the two sessions (F). NorBNI administration did not affect the increase in average duration of freezing episode observed between the Neutral and TMT sessions (G). Data pressented as mean +/- SEM. * Indicates p &lt; 0.05, *** indicates p &lt; 0.001." width="1425" />
<p class="caption">
Figure 3.1: Kappa-opioid receptor antagonism modulates basal and stress-induced freezing. (A) CPP was conducted such that each mouse was exposed to TMT for 5-minutes on their preferred side of the behavioural testing apparatus. (B) NorBNI administration 24hours before testing increases basal freezing and decreases freezing during TMT presentation. (C) The number of freezing episodes was increased at Neutral by NorBNI administration. (D) NorBNI did not produce any changes in the average duration of freezing episode under basal conditions or during TMT exposure. All mice exhibit an increase in the % Freezing between the Neutral and TMT sessions (E), but only the saline group increased the number of freezing episodes between the two sessions (F). NorBNI administration did not affect the increase in average duration of freezing episode observed between the Neutral and TMT sessions (G). Data pressented as mean +/- SEM. * Indicates p &lt; 0.05, *** indicates p &lt; 0.001.
</p>
</div>
<div id="statistical-analyses" class="section level2 hasAnchor" number="3.1">
<h2><span class="header-section-number">3.1</span> Statistical Analyses<a href="freezing-behaviour-during-tmt-presentation.html#statistical-analyses" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div id="two-way-anova-on-freezing-behaivour" class="section level3 hasAnchor" number="3.1.1">
<h3><span class="header-section-number">3.1.1</span> Two-way ANOVA on Freezing behaivour<a href="freezing-behaviour-during-tmt-presentation.html#two-way-anova-on-freezing-behaivour" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1-1"><a href="freezing-behaviour-during-tmt-presentation.html#cb1-1" tabindex="-1"></a>a <span class="ot">&lt;-</span> <span class="fu">aov</span>(Frz_Tm <span class="sc">~</span> Drug <span class="sc">*</span> Task, <span class="at">data=</span>train_data)</span>
<span id="cb1-2"><a href="freezing-behaviour-during-tmt-presentation.html#cb1-2" tabindex="-1"></a><span class="fu">summary</span>(a)</span></code></pre></div>
<pre><code>##             Df Sum Sq Mean Sq F value  Pr(&gt;F)    
## Drug         1    340     340   0.555 0.45835    
## Task         1  95925   95925 156.610 &lt; 2e-16 ***
## Drug:Task    1   6511    6511  10.631 0.00165 ** 
## Residuals   78  47776     613                    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>We quantified freezing behaviour both during the neutral pairing and the TMT exposure to investigate whether Nor BNI administration affected basal or stress-induced levels of freezing.</p>
<p>We computed a 2x2 ANOVA with Drug (saline or Nor BNI) as the between-groups factor and timepoint (Neutral vs TMT) as the within-subjects variable. The omnibus test for this model indicated a significant main effect of timepoint (F(1,39) = 79.09, p &lt; 0.001) and a timepoint * Drug interaction (F(1,39) = 11.41, p &lt; 0.001). Follow- up comparisons of the significant interaction indicated that NorBNI-injected mice froze more than did controls during the Neutral exposure (p &lt; 0.001) and that Nor-BNI-injected mice spent less time freezing than controls during the TMT exposure (p = 0.042). Nevertheless, both groups spent more time freeing during TMT presentation than they had at Neutral (both p &lt; 0.001), suggesting that both groups exhibited an innate defensive response during the single 5-minute TMT session.</p>
<div class="sourceCode" id="cb3"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb3-1"><a href="freezing-behaviour-during-tmt-presentation.html#cb3-1" tabindex="-1"></a>a <span class="ot">&lt;-</span> <span class="fu">anova_test</span>(<span class="at">data=</span>train_data, <span class="at">dv=</span>Frz_Tm, <span class="at">wid=</span>ID, <span class="at">within =</span> Task, <span class="at">between =</span> Drug)</span>
<span id="cb3-2"><a href="freezing-behaviour-during-tmt-presentation.html#cb3-2" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">kable</span>(<span class="fu">get_anova_table</span>(a))</span></code></pre></div>
<table>
<thead>
<tr class="header">
<th align="left">Effect</th>
<th align="right">DFn</th>
<th align="right">DFd</th>
<th align="right">F</th>
<th align="right">p</th>
<th align="left">p&lt;.05</th>
<th align="right">ges</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Drug</td>
<td align="right">1</td>
<td align="right">39</td>
<td align="right">0.522</td>
<td align="right">0.474</td>
<td align="left"></td>
<td align="right">0.007</td>
</tr>
<tr class="even">
<td align="left">Task</td>
<td align="right">1</td>
<td align="right">39</td>
<td align="right">169.279</td>
<td align="right">0.000</td>
<td align="left">*</td>
<td align="right">0.670</td>
</tr>
<tr class="odd">
<td align="left">Drug:Task</td>
<td align="right">1</td>
<td align="right">39</td>
<td align="right">11.353</td>
<td align="right">0.002</td>
<td align="left">*</td>
<td align="right">0.120</td>
</tr>
</tbody>
</table>
<div class="sourceCode" id="cb4"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb4-1"><a href="freezing-behaviour-during-tmt-presentation.html#cb4-1" tabindex="-1"></a>b <span class="ot">&lt;-</span> train_data <span class="sc">%&gt;%</span></span>
<span id="cb4-2"><a href="freezing-behaviour-during-tmt-presentation.html#cb4-2" tabindex="-1"></a>  <span class="fu">group_by</span>(Drug)<span class="sc">%&gt;%</span></span>
<span id="cb4-3"><a href="freezing-behaviour-during-tmt-presentation.html#cb4-3" tabindex="-1"></a>  <span class="fu">pairwise_t_test</span>(</span>
<span id="cb4-4"><a href="freezing-behaviour-during-tmt-presentation.html#cb4-4" tabindex="-1"></a>  Frz_Tm <span class="sc">~</span> Task, <span class="at">paired =</span> <span class="cn">TRUE</span>,</span>
<span id="cb4-5"><a href="freezing-behaviour-during-tmt-presentation.html#cb4-5" tabindex="-1"></a>  <span class="at">p.adjust.method =</span> <span class="st">&quot;bonferroni&quot;</span></span>
<span id="cb4-6"><a href="freezing-behaviour-during-tmt-presentation.html#cb4-6" tabindex="-1"></a>  )</span>
<span id="cb4-7"><a href="freezing-behaviour-during-tmt-presentation.html#cb4-7" tabindex="-1"></a></span>
<span id="cb4-8"><a href="freezing-behaviour-during-tmt-presentation.html#cb4-8" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">kable</span>(b)</span></code></pre></div>
<table>
<colgroup>
<col width="10%" />
<col width="9%" />
<col width="10%" />
<col width="9%" />
<col width="4%" />
<col width="4%" />
<col width="14%" />
<col width="4%" />
<col width="8%" />
<col width="8%" />
<col width="17%" />
</colgroup>
<thead>
<tr class="header">
<th align="left">Drug</th>
<th align="left">.y.</th>
<th align="left">group1</th>
<th align="left">group2</th>
<th align="right">n1</th>
<th align="right">n2</th>
<th align="right">statistic</th>
<th align="right">df</th>
<th align="right">p</th>
<th align="right">p.adj</th>
<th align="left">p.adj.signif</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Saline</td>
<td align="left">Frz_Tm</td>
<td align="left">Neutral</td>
<td align="left">TMT</td>
<td align="right">20</td>
<td align="right">20</td>
<td align="right">-10.722043</td>
<td align="right">19</td>
<td align="right">0e+00</td>
<td align="right">0e+00</td>
<td align="left">****</td>
</tr>
<tr class="even">
<td align="left">Nor-BNI</td>
<td align="left">Frz_Tm</td>
<td align="left">Neutral</td>
<td align="left">TMT</td>
<td align="right">21</td>
<td align="right">21</td>
<td align="right">-7.409239</td>
<td align="right">20</td>
<td align="right">4e-07</td>
<td align="right">4e-07</td>
<td align="left">****</td>
</tr>
</tbody>
</table>
<div class="sourceCode" id="cb5"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb5-1"><a href="freezing-behaviour-during-tmt-presentation.html#cb5-1" tabindex="-1"></a>c <span class="ot">&lt;-</span> train_data <span class="sc">%&gt;%</span></span>
<span id="cb5-2"><a href="freezing-behaviour-during-tmt-presentation.html#cb5-2" tabindex="-1"></a>  <span class="fu">group_by</span>(Task)<span class="sc">%&gt;%</span></span>
<span id="cb5-3"><a href="freezing-behaviour-during-tmt-presentation.html#cb5-3" tabindex="-1"></a>  <span class="fu">pairwise_t_test</span>(</span>
<span id="cb5-4"><a href="freezing-behaviour-during-tmt-presentation.html#cb5-4" tabindex="-1"></a>  Frz_Tm <span class="sc">~</span> Drug, <span class="at">paired =</span> <span class="cn">FALSE</span>,</span>
<span id="cb5-5"><a href="freezing-behaviour-during-tmt-presentation.html#cb5-5" tabindex="-1"></a>  <span class="at">p.adjust.method =</span> <span class="st">&quot;bonferroni&quot;</span></span>
<span id="cb5-6"><a href="freezing-behaviour-during-tmt-presentation.html#cb5-6" tabindex="-1"></a>  )</span>
<span id="cb5-7"><a href="freezing-behaviour-during-tmt-presentation.html#cb5-7" tabindex="-1"></a></span>
<span id="cb5-8"><a href="freezing-behaviour-during-tmt-presentation.html#cb5-8" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">kable</span>(c)</span></code></pre></div>
<table style="width:100%;">
<colgroup>
<col width="10%" />
<col width="9%" />
<col width="9%" />
<col width="10%" />
<col width="3%" />
<col width="3%" />
<col width="11%" />
<col width="11%" />
<col width="11%" />
<col width="17%" />
</colgroup>
<thead>
<tr class="header">
<th align="left">Task</th>
<th align="left">.y.</th>
<th align="left">group1</th>
<th align="left">group2</th>
<th align="right">n1</th>
<th align="right">n2</th>
<th align="right">p</th>
<th align="left">p.signif</th>
<th align="right">p.adj</th>
<th align="left">p.adj.signif</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Neutral</td>
<td align="left">Frz_Tm</td>
<td align="left">Saline</td>
<td align="left">Nor-BNI</td>
<td align="right">20</td>
<td align="right">21</td>
<td align="right">0.000182</td>
<td align="left">***</td>
<td align="right">0.000182</td>
<td align="left">***</td>
</tr>
<tr class="even">
<td align="left">TMT</td>
<td align="left">Frz_Tm</td>
<td align="left">Saline</td>
<td align="left">Nor-BNI</td>
<td align="right">20</td>
<td align="right">21</td>
<td align="right">0.042000</td>
<td align="left">*</td>
<td align="right">0.042000</td>
<td align="left">*</td>
</tr>
</tbody>
</table>
<p>We also computed ANOVA with the number of freezing episodes during each session entered as the dependent variable. This model also indicated a Drug * Timepoint interaction (F(1,39) = 13.17, p &lt; 0.001). Saline-injected mice froze more often during the TMT session than the Neutral session (p &lt; 0.001) whereas there was no difference in freezing frequency between the two sessions for NorBNI-injected mice (p = 0.28). Moreover, NorBNI-injected mice froze more often than did saline controls during the neutral exposure (p &lt; 0.001), but there was no difference in freezing frequency between the groups during the TMT session (p = 0.09).</p>
<div class="sourceCode" id="cb6"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb6-1"><a href="freezing-behaviour-during-tmt-presentation.html#cb6-1" tabindex="-1"></a>a <span class="ot">&lt;-</span> <span class="fu">anova_test</span>(<span class="at">data=</span>train_data, <span class="at">dv=</span>Frz_Freq, <span class="at">wid=</span>ID, <span class="at">within =</span> Task, <span class="at">between =</span> Drug)</span>
<span id="cb6-2"><a href="freezing-behaviour-during-tmt-presentation.html#cb6-2" tabindex="-1"></a><span class="fu">get_anova_table</span>(a)</span></code></pre></div>
<pre><code>## ANOVA Table (type III tests)
## 
##      Effect DFn DFd      F        p p&lt;.05   ges
## 1      Drug   1  39  1.602 2.13e-01       0.019
## 2      Task   1  39 29.078 3.61e-06     * 0.286
## 3 Drug:Task   1  39 13.170 8.15e-04     * 0.153</code></pre>
<div class="sourceCode" id="cb8"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb8-1"><a href="freezing-behaviour-during-tmt-presentation.html#cb8-1" tabindex="-1"></a>b <span class="ot">&lt;-</span> train_data <span class="sc">%&gt;%</span></span>
<span id="cb8-2"><a href="freezing-behaviour-during-tmt-presentation.html#cb8-2" tabindex="-1"></a>  <span class="fu">group_by</span>(Drug)<span class="sc">%&gt;%</span></span>
<span id="cb8-3"><a href="freezing-behaviour-during-tmt-presentation.html#cb8-3" tabindex="-1"></a>  <span class="fu">pairwise_t_test</span>(</span>
<span id="cb8-4"><a href="freezing-behaviour-during-tmt-presentation.html#cb8-4" tabindex="-1"></a>  Frz_Freq <span class="sc">~</span> Task, <span class="at">paired =</span> <span class="cn">TRUE</span>,</span>
<span id="cb8-5"><a href="freezing-behaviour-during-tmt-presentation.html#cb8-5" tabindex="-1"></a>  <span class="at">p.adjust.method =</span> <span class="st">&quot;bonferroni&quot;</span></span>
<span id="cb8-6"><a href="freezing-behaviour-during-tmt-presentation.html#cb8-6" tabindex="-1"></a>  )</span>
<span id="cb8-7"><a href="freezing-behaviour-during-tmt-presentation.html#cb8-7" tabindex="-1"></a></span>
<span id="cb8-8"><a href="freezing-behaviour-during-tmt-presentation.html#cb8-8" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">kable</span>(b)</span></code></pre></div>
<table>
<colgroup>
<col width="9%" />
<col width="10%" />
<col width="9%" />
<col width="8%" />
<col width="3%" />
<col width="3%" />
<col width="12%" />
<col width="3%" />
<col width="10%" />
<col width="10%" />
<col width="15%" />
</colgroup>
<thead>
<tr class="header">
<th align="left">Drug</th>
<th align="left">.y.</th>
<th align="left">group1</th>
<th align="left">group2</th>
<th align="right">n1</th>
<th align="right">n2</th>
<th align="right">statistic</th>
<th align="right">df</th>
<th align="right">p</th>
<th align="right">p.adj</th>
<th align="left">p.adj.signif</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Saline</td>
<td align="left">Frz_Freq</td>
<td align="left">Neutral</td>
<td align="left">TMT</td>
<td align="right">20</td>
<td align="right">20</td>
<td align="right">-7.644742</td>
<td align="right">19</td>
<td align="right">3.00e-07</td>
<td align="right">3.00e-07</td>
<td align="left">****</td>
</tr>
<tr class="even">
<td align="left">Nor-BNI</td>
<td align="left">Frz_Freq</td>
<td align="left">Neutral</td>
<td align="left">TMT</td>
<td align="right">21</td>
<td align="right">21</td>
<td align="right">-1.105378</td>
<td align="right">20</td>
<td align="right">2.82e-01</td>
<td align="right">2.82e-01</td>
<td align="left">ns</td>
</tr>
</tbody>
</table>
<div class="sourceCode" id="cb9"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb9-1"><a href="freezing-behaviour-during-tmt-presentation.html#cb9-1" tabindex="-1"></a>c <span class="ot">&lt;-</span> train_data <span class="sc">%&gt;%</span></span>
<span id="cb9-2"><a href="freezing-behaviour-during-tmt-presentation.html#cb9-2" tabindex="-1"></a>  <span class="fu">group_by</span>(Task)<span class="sc">%&gt;%</span></span>
<span id="cb9-3"><a href="freezing-behaviour-during-tmt-presentation.html#cb9-3" tabindex="-1"></a>  <span class="fu">pairwise_t_test</span>(</span>
<span id="cb9-4"><a href="freezing-behaviour-during-tmt-presentation.html#cb9-4" tabindex="-1"></a>  Frz_Freq <span class="sc">~</span> Drug, <span class="at">paired =</span> <span class="cn">FALSE</span>,</span>
<span id="cb9-5"><a href="freezing-behaviour-during-tmt-presentation.html#cb9-5" tabindex="-1"></a>  <span class="at">p.adjust.method =</span> <span class="st">&quot;bonferroni&quot;</span></span>
<span id="cb9-6"><a href="freezing-behaviour-during-tmt-presentation.html#cb9-6" tabindex="-1"></a>  )</span>
<span id="cb9-7"><a href="freezing-behaviour-during-tmt-presentation.html#cb9-7" tabindex="-1"></a></span>
<span id="cb9-8"><a href="freezing-behaviour-during-tmt-presentation.html#cb9-8" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">kable</span>(c)</span></code></pre></div>
<table>
<colgroup>
<col width="10%" />
<col width="11%" />
<col width="9%" />
<col width="10%" />
<col width="3%" />
<col width="3%" />
<col width="10%" />
<col width="11%" />
<col width="10%" />
<col width="17%" />
</colgroup>
<thead>
<tr class="header">
<th align="left">Task</th>
<th align="left">.y.</th>
<th align="left">group1</th>
<th align="left">group2</th>
<th align="right">n1</th>
<th align="right">n2</th>
<th align="right">p</th>
<th align="left">p.signif</th>
<th align="right">p.adj</th>
<th align="left">p.adj.signif</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Neutral</td>
<td align="left">Frz_Freq</td>
<td align="left">Saline</td>
<td align="left">Nor-BNI</td>
<td align="right">20</td>
<td align="right">21</td>
<td align="right">0.00065</td>
<td align="left">***</td>
<td align="right">0.00065</td>
<td align="left">***</td>
</tr>
<tr class="even">
<td align="left">TMT</td>
<td align="left">Frz_Freq</td>
<td align="left">Saline</td>
<td align="left">Nor-BNI</td>
<td align="right">20</td>
<td align="right">21</td>
<td align="right">0.09460</td>
<td align="left">ns</td>
<td align="right">0.09460</td>
<td align="left">ns</td>
</tr>
</tbody>
</table>
<p>ANOVA on the average duration of freezing episode indicated a significant main effect of timepoint (F(1,39) = 103.45, p &lt; 0.001) that did not interact with drug treatment (p = 0.24). The average duration of freezing episode was increased by TMT.</p>
<div class="sourceCode" id="cb10"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb10-1"><a href="freezing-behaviour-during-tmt-presentation.html#cb10-1" tabindex="-1"></a>a <span class="ot">&lt;-</span> <span class="fu">anova_test</span>(<span class="at">data=</span>train_data, <span class="at">dv=</span>Av_Dur, <span class="at">wid=</span>ID, <span class="at">within =</span> Task, <span class="at">between =</span> Drug)</span>
<span id="cb10-2"><a href="freezing-behaviour-during-tmt-presentation.html#cb10-2" tabindex="-1"></a><span class="fu">get_anova_table</span>(a)</span></code></pre></div>
<pre><code>## ANOVA Table (type III tests)
## 
##      Effect DFn DFd       F        p p&lt;.05      ges
## 1      Drug   1  39   0.029 8.66e-01       0.000396
## 2      Task   1  39 103.456 1.58e-12     * 0.553000
## 3 Drug:Task   1  39   1.452 2.35e-01       0.017000</code></pre>
<div class="sourceCode" id="cb12"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb12-1"><a href="freezing-behaviour-during-tmt-presentation.html#cb12-1" tabindex="-1"></a>b <span class="ot">&lt;-</span> train_data <span class="sc">%&gt;%</span></span>
<span id="cb12-2"><a href="freezing-behaviour-during-tmt-presentation.html#cb12-2" tabindex="-1"></a>  <span class="fu">group_by</span>(Drug)<span class="sc">%&gt;%</span></span>
<span id="cb12-3"><a href="freezing-behaviour-during-tmt-presentation.html#cb12-3" tabindex="-1"></a>  <span class="fu">pairwise_t_test</span>(</span>
<span id="cb12-4"><a href="freezing-behaviour-during-tmt-presentation.html#cb12-4" tabindex="-1"></a>  Av_Dur <span class="sc">~</span> Task, <span class="at">paired =</span> <span class="cn">TRUE</span>,</span>
<span id="cb12-5"><a href="freezing-behaviour-during-tmt-presentation.html#cb12-5" tabindex="-1"></a>  <span class="at">p.adjust.method =</span> <span class="st">&quot;bonferroni&quot;</span></span>
<span id="cb12-6"><a href="freezing-behaviour-during-tmt-presentation.html#cb12-6" tabindex="-1"></a>  )</span>
<span id="cb12-7"><a href="freezing-behaviour-during-tmt-presentation.html#cb12-7" tabindex="-1"></a></span>
<span id="cb12-8"><a href="freezing-behaviour-during-tmt-presentation.html#cb12-8" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">kable</span>(b)</span></code></pre></div>
<table style="width:100%;">
<colgroup>
<col width="10%" />
<col width="8%" />
<col width="10%" />
<col width="8%" />
<col width="3%" />
<col width="3%" />
<col width="12%" />
<col width="3%" />
<col width="10%" />
<col width="10%" />
<col width="16%" />
</colgroup>
<thead>
<tr class="header">
<th align="left">Drug</th>
<th align="left">.y.</th>
<th align="left">group1</th>
<th align="left">group2</th>
<th align="right">n1</th>
<th align="right">n2</th>
<th align="right">statistic</th>
<th align="right">df</th>
<th align="right">p</th>
<th align="right">p.adj</th>
<th align="left">p.adj.signif</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Saline</td>
<td align="left">Av_Dur</td>
<td align="left">Neutral</td>
<td align="left">TMT</td>
<td align="right">20</td>
<td align="right">20</td>
<td align="right">-6.971897</td>
<td align="right">19</td>
<td align="right">1.2e-06</td>
<td align="right">1.2e-06</td>
<td align="left">****</td>
</tr>
<tr class="even">
<td align="left">Nor-BNI</td>
<td align="left">Av_Dur</td>
<td align="left">Neutral</td>
<td align="left">TMT</td>
<td align="right">21</td>
<td align="right">21</td>
<td align="right">-7.589131</td>
<td align="right">20</td>
<td align="right">3.0e-07</td>
<td align="right">3.0e-07</td>
<td align="left">****</td>
</tr>
</tbody>
</table>
<div class="sourceCode" id="cb13"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb13-1"><a href="freezing-behaviour-during-tmt-presentation.html#cb13-1" tabindex="-1"></a>c <span class="ot">&lt;-</span> train_data <span class="sc">%&gt;%</span></span>
<span id="cb13-2"><a href="freezing-behaviour-during-tmt-presentation.html#cb13-2" tabindex="-1"></a>  <span class="fu">group_by</span>(Task)<span class="sc">%&gt;%</span></span>
<span id="cb13-3"><a href="freezing-behaviour-during-tmt-presentation.html#cb13-3" tabindex="-1"></a>  <span class="fu">pairwise_t_test</span>(</span>
<span id="cb13-4"><a href="freezing-behaviour-during-tmt-presentation.html#cb13-4" tabindex="-1"></a>  Av_Dur <span class="sc">~</span> Drug, <span class="at">paired =</span> <span class="cn">FALSE</span>,</span>
<span id="cb13-5"><a href="freezing-behaviour-during-tmt-presentation.html#cb13-5" tabindex="-1"></a>  <span class="at">p.adjust.method =</span> <span class="st">&quot;bonferroni&quot;</span></span>
<span id="cb13-6"><a href="freezing-behaviour-during-tmt-presentation.html#cb13-6" tabindex="-1"></a>  )</span>
<span id="cb13-7"><a href="freezing-behaviour-during-tmt-presentation.html#cb13-7" tabindex="-1"></a></span>
<span id="cb13-8"><a href="freezing-behaviour-during-tmt-presentation.html#cb13-8" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">kable</span>(c)</span></code></pre></div>
<table>
<colgroup>
<col width="10%" />
<col width="9%" />
<col width="9%" />
<col width="10%" />
<col width="4%" />
<col width="4%" />
<col width="10%" />
<col width="12%" />
<col width="10%" />
<col width="17%" />
</colgroup>
<thead>
<tr class="header">
<th align="left">Task</th>
<th align="left">.y.</th>
<th align="left">group1</th>
<th align="left">group2</th>
<th align="right">n1</th>
<th align="right">n2</th>
<th align="right">p</th>
<th align="left">p.signif</th>
<th align="right">p.adj</th>
<th align="left">p.adj.signif</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Neutral</td>
<td align="left">Av_Dur</td>
<td align="left">Saline</td>
<td align="left">Nor-BNI</td>
<td align="right">20</td>
<td align="right">21</td>
<td align="right">0.00381</td>
<td align="left">**</td>
<td align="right">0.00381</td>
<td align="left">**</td>
</tr>
<tr class="even">
<td align="left">TMT</td>
<td align="left">Av_Dur</td>
<td align="left">Saline</td>
<td align="left">Nor-BNI</td>
<td align="right">20</td>
<td align="right">21</td>
<td align="right">0.50100</td>
<td align="left">ns</td>
<td align="right">0.50100</td>
<td align="left">ns</td>
</tr>
</tbody>
</table>
<p>Taken together, these findings indicate that NorBNI administration increases time spent freezing at Neutral by increasing the frequency of bouts of freezing. TMT exposure increases both the frequency and average duration of bouts of freezing among naive mice, and the magnitude of the change in freezing behaviour is reduced among NorBNI treated mice.</p>
</div>
<div id="regressions" class="section level3 hasAnchor" number="3.1.2">
<h3><span class="header-section-number">3.1.2</span> Regressions<a href="freezing-behaviour-during-tmt-presentation.html#regressions" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<pre><code>## 
## Call:
## lm(formula = Perc ~ Frz_Freq * Drug, data = BL_data)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -2.8267 -0.7702 -0.1686  0.3901  8.3884 
## 
## Coefficients:
##                      Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)           0.35976    1.03281   0.348 0.729567    
## Frz_Freq              0.23889    0.06017   3.970 0.000318 ***
## DrugNor-BNI          -1.78723    1.40227  -1.275 0.210422    
## Frz_Freq:DrugNor-BNI  0.15621    0.06761   2.311 0.026535 *  
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 1.804 on 37 degrees of freedom
## Multiple R-squared:  0.8815, Adjusted R-squared:  0.8719 
## F-statistic: 91.78 on 3 and 37 DF,  p-value: &lt; 2.2e-16</code></pre>
<pre><code>## 
## Call:
## lm(formula = Perc ~ Frz_Freq * Drug, data = b)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -2.8267 -0.7702 -0.1686  0.3901  8.3884 
## 
## Coefficients:
##                     Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)         -1.42747    0.94851  -1.505   0.1408    
## Frz_Freq             0.39510    0.03082  12.820 3.51e-15 ***
## DrugSaline           1.78723    1.40227   1.275   0.2104    
## Frz_Freq:DrugSaline -0.15621    0.06761  -2.311   0.0265 *  
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 1.804 on 37 degrees of freedom
## Multiple R-squared:  0.8815, Adjusted R-squared:  0.8719 
## F-statistic: 91.78 on 3 and 37 DF,  p-value: &lt; 2.2e-16</code></pre>
<p>A regression model with Percent freezing during the Neutral session entered as the dependent variable and freezing frequency entered as the independent variable accounted for 87% of the variability in freezing (F(3,37) = 91.78, Adjusted R^2 = 0.87, p &lt; 0.001). Simple effects for this model indicated a significant main effect of Freezing Frequency (t = 3.97, p &lt; 0.001) and a significant Frequency * Drug interaction (t = 2.33, p = 0.026). Evaluation of the simple slopes for each drug condition indicated that for saline-treated mice, a 10-unit increase in freezing frequency was associated with a 2.3% increase in total time freezing. Among NorBNI-treated mice, a 10-unit increase in freezing was associated with a 3.9% increase in total time freezing.</p>
<pre><code>## 
## Call:
## lm(formula = Perc ~ Frz_Freq * Drug, data = TMTs)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -26.5697  -7.2100   0.5262   9.3678  23.8668 
## 
## Coefficients:
##                      Estimate Std. Error t value Pr(&gt;|t|)   
## (Intercept)           26.5527     9.5304   2.786  0.00837 **
## Frz_Freq               0.3165     0.2349   1.347  0.18607   
## DrugNor-BNI          -12.8500    13.1699  -0.976  0.33554   
## Frz_Freq:DrugNor-BNI   0.1866     0.3551   0.525  0.60249   
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 12.79 on 37 degrees of freedom
## Multiple R-squared:  0.2159, Adjusted R-squared:  0.1523 
## F-statistic: 3.395 on 3 and 37 DF,  p-value: 0.02779</code></pre>
<div class="sourceCode" id="cb17"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb17-1"><a href="freezing-behaviour-during-tmt-presentation.html#cb17-1" tabindex="-1"></a><span class="co"># Model 2: X=Av_Dur, y=Perc</span></span>
<span id="cb17-2"><a href="freezing-behaviour-during-tmt-presentation.html#cb17-2" tabindex="-1"></a>a <span class="ot">&lt;-</span> <span class="fu">lm</span>(Perc<span class="sc">~</span>Av_Dur <span class="sc">*</span> Drug, <span class="at">data=</span>BL_data)</span>
<span id="cb17-3"><a href="freezing-behaviour-during-tmt-presentation.html#cb17-3" tabindex="-1"></a><span class="fu">summary</span>(a)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = Perc ~ Av_Dur * Drug, data = BL_data)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -7.8633 -1.6178 -0.8294  1.2113 10.2455 
## 
## Coefficients:
##                    Estimate Std. Error t value Pr(&gt;|t|)  
## (Intercept)         -0.1638     2.8444  -0.058   0.9544  
## Av_Dur               6.6422     4.2461   1.564   0.1263  
## DrugNor-BNI         -5.6693     4.2286  -1.341   0.1882  
## Av_Dur:DrugNor-BNI  12.0048     5.6131   2.139   0.0391 *
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 3.292 on 37 degrees of freedom
## Multiple R-squared:  0.6058, Adjusted R-squared:  0.5738 
## F-statistic: 18.95 on 3 and 37 DF,  p-value: 1.3e-07</code></pre>
<div class="sourceCode" id="cb19"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb19-1"><a href="freezing-behaviour-during-tmt-presentation.html#cb19-1" tabindex="-1"></a><span class="co"># Re-order the &quot;drug&quot; variable to get the intercept for the NorBNI group.</span></span>
<span id="cb19-2"><a href="freezing-behaviour-during-tmt-presentation.html#cb19-2" tabindex="-1"></a>b <span class="ot">&lt;-</span> BL_data</span>
<span id="cb19-3"><a href="freezing-behaviour-during-tmt-presentation.html#cb19-3" tabindex="-1"></a>b<span class="sc">$</span>Drug <span class="ot">&lt;-</span> <span class="fu">as.character</span>(b<span class="sc">$</span>Drug)</span>
<span id="cb19-4"><a href="freezing-behaviour-during-tmt-presentation.html#cb19-4" tabindex="-1"></a>b<span class="sc">$</span>Drug <span class="ot">&lt;-</span> <span class="fu">factor</span>(b<span class="sc">$</span>Drug,<span class="at">levels =</span> <span class="fu">c</span>(<span class="st">&quot;Nor-BNI&quot;</span>,<span class="st">&quot;Saline&quot;</span>))</span>
<span id="cb19-5"><a href="freezing-behaviour-during-tmt-presentation.html#cb19-5" tabindex="-1"></a></span>
<span id="cb19-6"><a href="freezing-behaviour-during-tmt-presentation.html#cb19-6" tabindex="-1"></a><span class="co"># A regression model on Neutral Freezing</span></span>
<span id="cb19-7"><a href="freezing-behaviour-during-tmt-presentation.html#cb19-7" tabindex="-1"></a>a <span class="ot">&lt;-</span> <span class="fu">lm</span>(Perc<span class="sc">~</span>Av_Dur <span class="sc">*</span> Drug, <span class="at">data=</span>b)</span>
<span id="cb19-8"><a href="freezing-behaviour-during-tmt-presentation.html#cb19-8" tabindex="-1"></a><span class="fu">summary</span>(a)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = Perc ~ Av_Dur * Drug, data = b)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -7.8633 -1.6178 -0.8294  1.2113 10.2455 
## 
## Coefficients:
##                   Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)         -5.833      3.129  -1.864   0.0702 .  
## Av_Dur              18.647      3.671   5.079  1.1e-05 ***
## DrugSaline           5.669      4.229   1.341   0.1882    
## Av_Dur:DrugSaline  -12.005      5.613  -2.139   0.0391 *  
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 3.292 on 37 degrees of freedom
## Multiple R-squared:  0.6058, Adjusted R-squared:  0.5738 
## F-statistic: 18.95 on 3 and 37 DF,  p-value: 1.3e-07</code></pre>

</div>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="generate-a-timeline-of-experimental-proceedings.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="conditioned-place-aversion-to-tmt.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/USERNAME/REPO/edit/BRANCH/03-GP_TMT_Freezing.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["_main.pdf", "_main.epub"],
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "subsection"
}
});
});
</script>

</body>

</html>
